name: LAGraph CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config:
         - {grb_version: 6.0.0, conda_grb_package_hash: h9c3ff4c}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install tools for build
      run: |
        sudo apt install -y lcov
    - name: Get GraphBLAS binaries
      run: |
        mkdir graphblas-binaries
        cd graphblas-binaries
        wget --quiet https://anaconda.org/conda-forge/graphblas/${{ matrix.config.grb_version }}/download/linux-64/graphblas-${{ matrix.config.grb_version }}-${{ matrix.config.conda_grb_package_hash }}_0.tar.bz2
        tar xf graphblas-${{ matrix.config.grb_version }}-${{ matrix.config.conda_grb_package_hash }}_0.tar.bz2
        cd ..
    - name: Build project
      run: |
        export GRAPHBLAS_INCLUDE_DIR=`pwd`/graphblas-binaries/include
        export GRAPHBLAS_LIBRARY=`pwd`/graphblas-binaries/lib/libgraphblas.so
        mkdir build
        cd build
        cmake .. -DCOVERAGE=1 -DGRAPHBLAS_INCLUDE_DIR=${GRAPHBLAS_INCLUDE_DIR} -DGRAPHBLAS_LIBRARY=${GRAPHBLAS_LIBRARY}
        JOBS=2 make
        make test_coverage
  macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        config:
         - {grb_version: 6.0.0, conda_grb_package_hash: h4a89273}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Get GraphBLAS binaries
      run: |
        mkdir graphblas-binaries
        cd graphblas-binaries
        wget --quiet https://anaconda.org/conda-forge/graphblas/${{ matrix.config.grb_version }}/download/osx-64/graphblas-${{ matrix.config.grb_version }}-${{ matrix.config.conda_grb_package_hash }}_0.tar.bz2
        tar xf graphblas-${{ matrix.config.grb_version }}-${{ matrix.config.conda_grb_package_hash }}_0.tar.bz2
        cd ..
    - name: Build project
      run: |
        export GRAPHBLAS_INCLUDE_DIR=`pwd`/graphblas-binaries/include
        export GRAPHBLAS_LIBRARY=`pwd`/graphblas-binaries/lib/libgraphblas.dylib
        mkdir build
        cd build
        CC=gcc-11 CXX=g++-11 cmake .. -DGRAPHBLAS_INCLUDE_DIR=${GRAPHBLAS_INCLUDE_DIR} -DGRAPHBLAS_LIBRARY=${GRAPHBLAS_LIBRARY}
        JOBS=2 make
        make test
